"use client";

import { useEffect, useMemo, useState } from "react";
import { LegalFooter } from "@/components/legal/LegalFooter";
import type { BingoActivity, BingoItem } from "@/lib/bingo";

function hash(text: string) { let value = 2166136261; for (let i = 0; i < text.length; i++) { value ^= text.charCodeAt(i); value = Math.imul(value, 16777619); } return value >>> 0; }
function shuffle(items: BingoItem[], seedValue: number) { const result = [...items]; let seed = seedValue || 1; const random = () => ((seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0) / 4294967296); for (let i = result.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; }
function completedLines(marked: boolean[], size: number) { const lines: number[][] = []; for (let row=0; row<size; row++) lines.push(Array.from({length:size},(_,c)=>row*size+c)); for (let col=0; col<size; col++) lines.push(Array.from({length:size},(_,r)=>r*size+col)); lines.push(Array.from({length:size},(_,i)=>i*size+i),Array.from({length:size},(_,i)=>i*size+(size-1-i))); return lines.filter(line=>line.every(index=>marked[index])); }

export default function BingoPlayer({ activityId }: { activityId: string }) {
  const [game, setGame] = useState<BingoActivity | null>(null); const [error, setError] = useState("");
  const [participant, setParticipant] = useState(""); const [round, setRound] = useState(0); const [answers, setAnswers] = useState<Record<number,string>>({}); const [active, setActive] = useState<number | null>(null);
  useEffect(() => { fetch(`/api/bingo/${activityId}`).then(async response => { const data=await response.json(); if(!response.ok) throw new Error(data.error); setGame(data); const key=`uniplay_bingo_player_${activityId}`; let id=localStorage.getItem(key); if(!id){ id=crypto.randomUUID(); localStorage.setItem(key,id); } setParticipant(id); const saved=JSON.parse(localStorage.getItem(`${key}_state`)||"null"); if(saved){ setRound(saved.round||0); setAnswers(saved.answers||{}); } }).catch(reason=>setError(reason.message||"Не удалось открыть игру")); },[activityId]);
  const cells = useMemo(() => { if(!game||!participant) return []; const count=game.gridSize*game.gridSize-(game.freeCell?1:0); const chosen=shuffle(game.items,hash(`${game.id}:${participant}:${round}`)).slice(0,count); if(game.freeCell) chosen.splice(Math.floor(game.gridSize*game.gridSize/2),0,{id:"free",label:"FREE SPACE",prompt:""}); return chosen; },[game,participant,round]);
  function persist(next: Record<number,string>, nextRound=round){ setAnswers(next); localStorage.setItem(`uniplay_bingo_player_${activityId}_state`,JSON.stringify({round:nextRound,answers:next})); }
  if(error) return <main className="grid min-h-screen place-items-center bg-[#fff8ec] p-6"><div className="rounded-3xl bg-white p-8 text-center shadow-xl"><div className="text-5xl">🎯</div><h1 className="mt-4 text-2xl font-black">{error}</h1><p className="mt-2 text-slate-500">Проверьте код или попросите новую ссылку у учителя.</p></div></main>;
  if(!game) return <main className="grid min-h-screen place-items-center bg-[#fff8ec] text-xl font-black">Загружаем карточку…</main>;
  const marked=cells.map((cell,index)=>cell.id==="free"||Boolean(answers[index])); const lines=completedLines(marked,game.gridSize); const won=game.winCondition==="full"?marked.every(Boolean):lines.length>0;
  return <div className="min-h-screen bg-[#fff8ec] text-[#17324d]"><main className="mx-auto max-w-6xl p-3 sm:p-6"><header className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-3xl bg-white p-5 shadow-xl"><div><span className="text-sm font-black text-blue-600">Код игры: {game.id}</span><h1 className="text-2xl font-black sm:text-4xl">{game.title}</h1><p className="mt-1 text-slate-600">{game.instructions||"Задай вопрос. Услышал Yes — впиши имя."}</p></div><div className="flex gap-2"><span className="rounded-full bg-blue-50 px-4 py-2 font-black">Отмечено: {marked.filter(Boolean).length}/{marked.length}</span>{game.allowNewCard&&<button onClick={()=>{const next=round+1;setRound(next);persist({},next)}} className="rounded-full bg-blue-600 px-4 py-2 font-black text-white">Новая карточка</button>}</div></header>
    {won&&<div className="mb-4 rounded-2xl bg-amber-300 p-4 text-center text-3xl font-black shadow-lg">🎉 BINGO!</div>}
    <section className="grid gap-2 rounded-3xl bg-white/70 p-2 shadow-xl sm:gap-3 sm:p-4" style={{gridTemplateColumns:`repeat(${game.gridSize},minmax(0,1fr))`}}>{cells.map((cell,index)=><button key={`${cell.id}_${index}`} disabled={cell.id==="free"} onClick={()=>setActive(index)} className={`relative flex aspect-square min-w-0 flex-col items-center justify-center overflow-hidden rounded-xl border-2 p-1 text-center text-[10px] font-black leading-tight transition sm:rounded-2xl sm:p-3 sm:text-base ${cell.id==="free"?"border-amber-400 bg-amber-100":answers[index]?"border-emerald-500 bg-emerald-50 text-emerald-800":"border-slate-200 bg-white hover:border-blue-500"}`}><span>{cell.label}</span>{answers[index]&&<span className="mt-1 max-w-full truncate rounded-full bg-white px-2 py-1 text-[9px] text-emerald-700 sm:text-xs">✓ {answers[index]}</span>}</button>)}</section>
    {active!==null&&<div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/60 p-4" onClick={()=>setActive(null)}><form onSubmit={e=>{e.preventDefault();const value=String(new FormData(e.currentTarget).get("name")||"").trim();if(value){persist({...answers,[active]:value});setActive(null)}}} onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-3xl bg-white p-7 text-center shadow-2xl"><p className="text-sm font-black uppercase text-blue-600">Ask your classmate</p><h2 className="mt-2 text-3xl font-black">{cells[active].prompt}</h2><p className="mt-2 text-slate-500">Если ответ Yes, впиши имя.</p><input name="name" defaultValue={answers[active]||""} autoFocus maxLength={30} placeholder="Name" className="mt-5 w-full rounded-xl border-2 border-slate-200 px-4 py-3 text-lg outline-none focus:border-blue-500"/><button className="mt-3 w-full rounded-xl bg-emerald-600 px-4 py-3 font-black text-white">Готово</button>{answers[active]&&<button type="button" onClick={()=>{const next={...answers};delete next[active];persist(next);setActive(null)}} className="mt-2 w-full rounded-xl bg-slate-100 px-4 py-3 font-bold">Убрать отметку</button>}</form></div>}
  </main><LegalFooter /></div>;
}
